### ISSUE TITLE
About compounding error

### ISSUE THREAD

**Issue by suhwan-cho** [dukebw/SSTVOS#1]
Hi, thanks for your great work!

By the way, I don't understand the meaning of
"The dominant mask refinement and temporal feature propagation methods are recurrent. Due to their sequential nature, recurrent methods for VOS exhibit compounding error over time, and are not parallelizable across a single example.". 

From the perspective of "compounding error", what is the difference between SST and STM?

**Comment by dukebw** [comment]
Hi Suhwan, you are right that SST and STM resolve the compounding error problem in a similar way when compared with recurrent approaches. SST takes the viewpoint of sparse attention, while STM frames the problem as memory networks, but in both cases the current frame feature maps query a history of past frame feature maps. The decoder decodes the result.

I think one difference between SST and STM is not from the perspective of compounding error, but rather from sparsity. SST uses sparsity in the attention operator to improve scalability compared to full attention.

**Comment by suhwan-cho** [comment]
Thank you very much for your reply!
